### ISSUE TITLE
Erro no evento de teleporte para arena após selecionar o kit

### ISSUE THREAD

**Issue by iago-fragnan** [iagof-dev/N3rdyKits#1]
simplesmente não teleporta após escolher o kit

14,25% de acontecer isso

**Comment by iago-fragnan** [comment]
[19:22:29 WARN]: [N3rdyKits] Task #30 for N3rdyKits v1.0 generated an exception
java.lang.NullPointerException: null
        at com.n3rdydev.entity.player$1.run(player.java:179) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by iago-fragnan** [comment]
Aparentemente resolvido
